import win32com.client
import matplotlib.pyplot as plt
import time
dso = win32com.client.Dispatch('LeCroy.ActiveDSOCtrl.1')
dso.MakeConnection("IP:192.168.0.101")
#dso.WriteString("C1:START",1)
# dso.WriteString("C1:VDIV .60",1)
# dso.WriteString("C2:VDIV .60",1)
# dso.WriteString("C1:TRLV -0.4",1)
# dso.WriteString("C2:TRLV -1.1",1)
# dso.WriteString("C1:TRSL NEG",1)
# dso.WriteString("C2:TRSL NEG",1)
# dso.WriteString("C1:OFST 1.2",1)
# dso.WriteString("C2:OFST 1.2",1)
#dso.WriteString("C1:SEQ ON,10", True)
#dso.WriteString("SEQ OFF", 1)
#dso.WriteString("C1:TIME_DIV 20NS", 1)
#dso.WriteString("C2:TIME_DIV 20NS", 1)
dso.WriteString("TRSE?", True)
str1 = dso.ReadString(80)
#dso.WriteString("TRSE PA,HT,TI,HV,200E-9 S", True)
print(str1)
dso.WriteString("TRDL?", True)
str2 = dso.ReadString(80)
print(str2)
#dso.WriteString("VBS app.Measure.ShowMeasure = true",1)
#dso.WriteString("VBS app.Measure.ShowMeasure = false",1)
t0_1 = time.time()
i = 0
plt.ion()
plt.figure(1)
while i < 1:
    plt.clf()
    t1 = time.time()
    Waveform = dso.GetScaledWaveformWithTimes("C1",200000,0)
    t2 = time.time()
    print(list(Waveform[1]))
    #print(t2 - t1)
    #Waveform = []
    #print(Waveform)
    print(len(Waveform))
    plt.plot(Waveform[1])
    plt.pause(0.001)
    i=i+1
t0_2 = time.time()
print(t0_2-t0_1)
